# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(907, 750)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.verticalGroupBox)
        self.graphicsView.setEnabled(True)
        self.graphicsView.setMinimumSize(QtCore.QSize(640, 352))
        self.graphicsView.setMouseTracking(False)
        self.graphicsView.setAlignment(QtCore.Qt.AlignCenter)
        self.graphicsView.setViewportUpdateMode(QtWidgets.QGraphicsView.FullViewportUpdate)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.groupBox = QtWidgets.QGroupBox(self.verticalGroupBox)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.LE_start = QtWidgets.QLineEdit(self.groupBox)
        self.LE_start.setObjectName("LE_start")
        self.horizontalLayout_5.addWidget(self.LE_start)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.LE_end = QtWidgets.QLineEdit(self.groupBox)
        self.LE_end.setObjectName("LE_end")
        self.horizontalLayout_5.addWidget(self.LE_end)
        self.CheckBoxIsShowProc = QtWidgets.QCheckBox(self.groupBox)
        self.CheckBoxIsShowProc.setObjectName("CheckBoxIsShowProc")
        self.horizontalLayout_5.addWidget(self.CheckBoxIsShowProc)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.verticalGroupBox)
        self.label.setMinimumSize(QtCore.QSize(50, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEditInputPath = QtWidgets.QLineEdit(self.verticalGroupBox)
        self.lineEditInputPath.setReadOnly(True)
        self.lineEditInputPath.setObjectName("lineEditInputPath")
        self.horizontalLayout_3.addWidget(self.lineEditInputPath)
        self.pushButtonInputPath = QtWidgets.QPushButton(self.verticalGroupBox)
        self.pushButtonInputPath.setObjectName("pushButtonInputPath")
        self.horizontalLayout_3.addWidget(self.pushButtonInputPath)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEditOutputPath = QtWidgets.QLineEdit(self.verticalGroupBox)
        self.lineEditOutputPath.setReadOnly(True)
        self.lineEditOutputPath.setObjectName("lineEditOutputPath")
        self.horizontalLayout.addWidget(self.lineEditOutputPath)
        self.pushButtonOutputPath = QtWidgets.QPushButton(self.verticalGroupBox)
        self.pushButtonOutputPath.setObjectName("pushButtonOutputPath")
        self.horizontalLayout.addWidget(self.pushButtonOutputPath)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalGroupBox)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.verticalGroupBox)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.pushButtonStart = QtWidgets.QPushButton(self.verticalGroupBox)
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.horizontalLayout_2.addWidget(self.pushButtonStart)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButtonExit = QtWidgets.QPushButton(self.verticalGroupBox)
        self.pushButtonExit.setMaximumSize(QtCore.QSize(80, 30))
        self.pushButtonExit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButtonExit.setAutoFillBackground(True)
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.verticalLayout.addWidget(self.pushButtonExit)
        self.verticalLayout_2.addWidget(self.verticalGroupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 907, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_files = QtWidgets.QAction(MainWindow)
        self.actionOpen_files.setObjectName("actionOpen_files")
        self.actionOpen_folder = QtWidgets.QAction(MainWindow)
        self.actionOpen_folder.setObjectName("actionOpen_folder")
        self.actionAbout_Subtitle_Detector = QtWidgets.QAction(MainWindow)
        self.actionAbout_Subtitle_Detector.setObjectName("actionAbout_Subtitle_Detector")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_files)
        self.menuFile.addAction(self.actionOpen_folder)
        self.menuHelp.addAction(self.actionAbout_Subtitle_Detector)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Subtitle Detector"))
        self.label_3.setText(_translate("MainWindow", "开始帧："))
        self.label_4.setText(_translate("MainWindow", "结束帧："))
        self.CheckBoxIsShowProc.setText(_translate("MainWindow", "是否显示过程"))
        self.label.setText(_translate("MainWindow", "Input:"))
        self.pushButtonInputPath.setText(_translate("MainWindow", "  Select File  "))
        self.label_2.setText(_translate("MainWindow", "Output:"))
        self.pushButtonOutputPath.setText(_translate("MainWindow", "Select Folder"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\';\"></body></html>"))
        self.pushButtonStart.setText(_translate("MainWindow", "Start"))
        self.pushButtonExit.setText(_translate("MainWindow", "Exit"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen_files.setText(_translate("MainWindow", "Open File"))
        self.actionOpen_folder.setText(_translate("MainWindow", "Open Folder"))
        self.actionAbout_Subtitle_Detector.setText(_translate("MainWindow", "About Subtitle Detector"))
